# Generated by Django 6.0.1 on 2026-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('BETA', 'Beta Tester'), ('FREE', 'Free'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BETA', max_length=20),
        ),
    ]
