# Generated by Django 6.0.1 on 2026-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_storage_warning_level',
            field=models.IntegerField(default=0),
        ),
    ]
