# Generated by Django 6.0.1 on 2026-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_storage_warning_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_storage_usage',
            field=models.BigIntegerField(default=0),
        ),
    ]
