# Generated by Django 6.0.1 on 2026-01-21 17:23

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_current_storage_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.get_avatar_upload_path),
        ),
    ]
