# Generated by Django 6.0.1 on 2026-01-24 06:38

import accounts.utils
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=accounts.utils.get_avatar_upload_path),
        ),
    ]
