# Generated by Django 6.0.1 on 2026-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
