# Generated by Django 6.0.1 on 2026-01-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letter_context'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
