# Generated by Django 6.0.1 on 2026-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_alter_letter_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hant', 'Traditional Chinese'), ('zh-hans', 'Simplified Chinese'), ('th', 'Thai')], default='en-us', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'language')},
        ),
    ]
