# Generated by Django 6.0.1 on 2026-01-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.CharField(choices=[('section', 'Section (H2)'), ('subsection', 'Subsection (H3)'), ('subsubsection', 'Subsubsection (H4)')], default='section', help_text='Hierarchy level: section (h2), subsection (h3), etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent section (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='handouts.section'),
        ),
    ]
