# Generated by Django 6.0.1 on 2026-01-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0003_section_level_section_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown or Block JSON content'),
        ),
    ]
