# Generated by Django 6.0.1 on 2026-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0004_alter_section_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='handout',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Last PDF generation time', null=True),
        ),
    ]
