# Generated by Django 6.0.1 on 2026-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0005_handout_file_size_handout_last_downloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
