# Generated by Django 6.0.1 on 2026-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0006_handout_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Description for screen readers', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.CharField(blank=True, help_text='Visible title below the image', max_length=255),
        ),
    ]
