# Generated by Django 6.0.1 on 2026-01-24 06:38

import cloudinary_storage.storage
import handouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0007_attachment_alt_text_attachment_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=handouts.models.attachment_upload_path),
        ),
    ]
